### PR TITLE
Task DVD-382

### PR DESCRIPTION
**Pull request by TheoWolf**

### CODE REVIEW

**Comment by fraudies** [comment]
Can you try to create the VS solution directly in src/main/cpp (e.g. create solution from existing project) this way the solution and project will automatically include all the hpp/cpp files and these are directly in scope to be used in ffplay.c? Thanks

**Comment by fraudies** [comment]
I don't see the ffmpeg libraries setup under
Linker > Input > Additional Dependencies
(I see 'SDL2.lib' and 'SDL2main.lib' setup)
Do we have to add the following libs as well?
'avcodec.lib', 
'avdevice.lib', 
'avfilter.lib', 
'avformat.lib', 
'avutil.lib', 
'postproc.lib', 
'swresample.lib',
'swscale.lib'

**Comment by fraudies** [comment]
Also, we probably need to check in for now
SDL2.dll 
postproc... .dll
avfilter... .dll
Currently, this repo still has the setup for ffmpeg-3.4 in it's dll's.

I'm fine with switching to ffmpeg 4 if you'd like to replace the dll's in this repo.

**Comment by TheoWolf** [comment]
I will move the solution to main/cpp.

Yes, ffmpeg libraries should be added in Linker > Input > Additional Dependencies, I didn't change the properties of the solution. Don't know why it is not part of the project anymore.
'avcodec.lib',
'avdevice.lib',
'avfilter.lib',
'avformat.lib',
'avutil.lib',
'postproc.lib',
'swresample.lib',
'swscale.lib'

Currently, we are using FFmpeg 4.0 version in Datavyu (See the pom file on the master branch), However, ffmpeg-libs is not configured to build postproc and avfilter is not part of the artifact, but adding --enable-pp --enable-sdl2 to the ./configure will fix it

**Comment by fraudies** [comment]
Discussed offline on slack.  Let's switch this to a x86 compile.

For documentation to make this setup work 

1. (for now) please switch to the Debug x86 configuration in Visual Studio.

2. The change the following directories to your local setup
VC ++ Directories > Include Directories
VC ++ Directories > Library Directories

3. Copy the dll's to alongside the ffplay.c file
avcodec-58.dll
avdevice-58.dll
avfilter-7.dll
avformat-58.dll
avutil-56.dll
postproc-55.dll
SDL2.dll
swresample-3.dll
swscale-5.dll
For now these must be compiled for x86.

**Comment by fraudies** [comment]
Could you update this PR with the lib configuration for the Debug | x64 setting?

**Comment by TheoWolf** [comment]
I will link a confluence page to the JIRA ticket for both architectures (x86|x64)

**Pull request merged**
